### ISSUE TITLE
[Bug]: Can't run the tutorial commands of xslocobot description

### ISSUE THREAD

**Issue by Dorteel** [Interbotix/interbotix_ros_rovers#16]
### What happened?

Hello!

I'm trying to follow the LoCoBot Descriptions tutorials described in the [Documentation](https://trossenrobotics.com/docs/interbotix_xslocobots/ros_packages/locobot_descriptions.html), but when trying the first command I get an error in RViz saying that the transforms are missing. I'm running it on a locobot_wx250s.
![image](https://user-images.githubusercontent.com/16238582/170104363-fac40ca7-a0e8-419e-b1a6-05ec7c66671f.png)

### Robot Model

locobot_wx250s

### Operating System

Ubuntu 20.04

### Steps To Reproduce

I ssh-d into the robot and just ran
`roslaunch interbotix_xslocobot_descriptions xslocobot_description.launch robot_model:=locobot_wx200 use_joint_pub_gui:=true`

### Relevant log output

```shell
locobot@locobot:~$ roslaunch interbotix_xslocobot_descriptions xslocobot_description.launch robot_model:=locobot_wx250s use_joint_pub_gui:=true
... logging to /home/locobot/.ros/log/b29ce60a-db78-11ec-bc03-cb80ad3cf0e1/roslaunch-locobot-2156.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://10.15.3.56:44637/

SUMMARY
========

PARAMETERS
 * /locobot/robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.15.14

NODES
  /locobot/
    joint_state_publisher_gui (joint_state_publisher_gui/joint_state_publisher_gui)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)

ROS_MASTER_URI=http://10.15.3.55:11311/

process[locobot/joint_state_publisher_gui-1]: started with pid [2172]
process[locobot/robot_state_publisher-2]: started with pid [2173]
process[locobot/rviz-3]: started with pid [2174]
```

**Comment by LSinterbotix** [comment]
Hi @Dorteel. Could you provide the following:

- The Global Status warning
- The full text of any of the errors under the RobotModel display
- Is the joint_state_pub_gui publishing to the `/locobot_wx250s/joint_states` topic properly?
- Did you change any of the default networking settings on the robot or your remote computer?

**Comment by Dorteel** [comment]
Hi @LSinterbotix, Thanks for the quick reply!
When I started the robot this morning and ran the same script everything worked fine.
Not sure what happened..
