### ISSUE TITLE
[Bug]: Error running the pick_place_no_armtag.py demo due to bad argument InterbotixPointCloudInterface 

### ISSUE THREAD

**Issue by daniel-gheorghita** [Interbotix/interbotix_ros_rovers#19]
### What happened?

In interbotix_ros_toolboxes/blob/main/interbotix_xs_toolbox/interbotix_xs_modules/src/interbotix_xs_modules/locobot.py we see at line 95 <robot_name=robot_name + "/pc_filter"> while the InterbotixPointCloudInterface has these constructor arguments <def __init__(self, filter_ns="pc_filter", init_node=False)>. This raises an error when running pick_place_armtag.py or pick_place_no_armtag.py. Removing (or replacing with the correct argument name) <robot_name=> from locobot.py:95 seems to fix the problem. 

### Robot Model

locobot_wx200

### Operating System

Ubuntu 20.04

### ROS Distro

ROS1 Noetic

### Steps To Reproduce

I was following the Python Perception Youtube tutorial. The issue occurred when running pick_place_no_armtag.py or pick_place_armtag.py.

**Comment by LSinterbotix** [comment]
This should be fixed with the above commit. Feel free to reopen this issue if not.
