### ISSUE TITLE
[Bug]: Missing tf link

### ISSUE THREAD

**Issue by stephenadhi** [Interbotix/interbotix_ros_rovers#31]
### What happened?

Missing tf transformation from locobot/camera_tower_link to locobot/pan_link (frame somehow not detected). This causes the tf2 tree to split into two (see picture). 

![image](https://user-images.githubusercontent.com/32376039/217904625-643cd9a6-72eb-4305-adae-251b830a4c7b.png)

### Robot Model

INTERBOTIX_XSLOCOBOT_BASE_TYPE=kobuki

### Operating System

Ubuntu 22.04

### ROS Distro

ROS 2 Humble

### Steps To Reproduce

`ros2 launch interbotix_xslocobot_sim xslocobot_gz_classic.launch.py robot_model:=locobot_base robot_name:=locobot`

### Additional Info

Tried to directly load pan_and_tilt in locobot.urdf.xacro by removing the IF condition for camera_tower_size. Same tf2 tree result.

**Comment by LSinterbotix** [comment]
Let me know if f619f996f8c0b5413d2c7c1af8728976a88ea23c and 8a9c29117dbfac5ba936a229f042d03c14a6cab4 fix this issue.

**Comment by stephenadhi** [comment]
Yes, the missing link is solved now. Thanks for the quick response!
