### ISSUE TITLE
[Question]: Unable to reproduce Landmark-Based Navigation

### ISSUE THREAD

**Issue by fyyffy** [Interbotix/interbotix_ros_rovers#44]
### Question

I am trying to run the open source package [Landmark-Based Navigation](https://docs.trossenrobotics.com/interbotix_xslocobots_docs/ros1_packages/landmark_based_navigation.html).
Adding Landmarks and mapping are completed as per the instructions, but the commands under Localization are not executed as per the instructions.<img width="906" alt="80932277-FF3A-4B72-878F-96F9064F5F45" src="https://github.com/Interbotix/interbotix_ros_rovers/assets/130592348/3ddfc23a-70b2-477c-bf28-2fbfbcc8f08c">

A new terminal opens but closes after outputting the following.

![image](https://github.com/Interbotix/interbotix_ros_rovers/assets/130592348/20b2f4cb-dbdc-4d3e-a740-f7c27273066e)
![image](https://github.com/Interbotix/interbotix_ros_rovers/assets/130592348/8cf49ea7-c6d8-4ab3-8221-ecc597d7bde5)

The log seems to recognize kobuki, but it is actually create3.
Please help if you know the cause.

<img width="512" alt="スクリーンショット 2023-06-14 15 14 12" src="https://github.com/Interbotix/interbotix_ros_rovers/assets/130592348/44d3229b-c5f6-497a-aafc-0ab385dbb860">

In nav_to_landmark, model is described as px100.

### Robot Model

locobot_px100

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by lukeschmitt-tr** [comment]
1. What commits are your interbotix_ros_core, ..._ros_rovers, and ..._ros_toolboxes repos at?
2. Check that the `/<robot_name/base_type` parameter is set to `create3` and not `kobuki`.
3. Check your `INTERBOTIX_XSLOCOBOT_BASE_TYPE` environment variable.

**Comment by fyyffy** [comment]
1.Is this the correct information to provide?
<img width="478" alt="スクリーンショット 2023-06-16 9 45 33" src="https://github.com/Interbotix/interbotix_ros_rovers/assets/130592348/dd5ad63a-8807-45af-88ad-26c4dea32a66">

<img width="481" alt="スクリーンショット 2023-06-16 9 45 57" src="https://github.com/Interbotix/interbotix_ros_rovers/assets/130592348/6147ad28-c5cc-4dbd-b2bd-9734ae48cf64">

<img width="481" alt="スクリーンショット 2023-06-16 9 46 32" src="https://github.com/Interbotix/interbotix_ros_rovers/assets/130592348/341e788c-c6d7-42b9-866d-8fdb2e2eecbf">


2.create3 is displayed.
<img width="304" alt="スクリーンショット 2023-06-26 10 08 12" src="https://github.com/Interbotix/interbotix_ros_rovers/assets/130592348/fd3794d3-1062-4a4d-b6e8-9c7d5764f92d">


3.create3 is displayed.
<img width="332" alt="スクリーンショット 2023-06-16 9 44 59" src="https://github.com/Interbotix/interbotix_ros_rovers/assets/130592348/e3132425-dc7b-4909-86df-2b4be278f6fd">

Please let me know if you can find out anything.

**Comment by lukeschmitt-tr** [comment]
At the moment I would advise you to hardcore the base_type variable to `create3` in the [locobot.py](https://github.com/Interbotix/interbotix_ros_toolboxes/blob/45cc26d6e2c82cc1cd2b649eee0ff7676f63b3d0/interbotix_xs_toolbox/interbotix_xs_modules/src/interbotix_xs_modules/locobot.py#L60) file located in the traceback while we investigate this issue.

**Comment by fyyffy** [comment]
locobot.py was an earlier version, so I fixed it and it worked without error. Thank you.

This video is of locobot in action, is the gradual movement normal? Is the sloping floor the cause?

https://github.com/Interbotix/interbotix_ros_rovers/assets/130592348/f5f7ae8d-6383-4494-a91d-6ed410aa5315
