### ISSUE TITLE
[Question]: How to move the robot with LoCoBot Control Package or Publish Aligned Depth with Joystick Package

### ISSUE THREAD

**Issue by dwindy** [Interbotix/interbotix_ros_rovers#51]
### Question

Hi there,
I'm hoping to use the robot to gather some data, including RGB, Depth and LIDAR.
I was using **Joystick Control Package** but unfortunately found out that package didn't publish the topic of "**locobot/camera.aligned_depth_to_color/image_raw**".
The **aligned depth** would be found by using **LoCoBot Control Package** with argument align_depth:=true. 
(Which the Joystick Control Package didn't has this argument).

So I'm wondering, How to make the robot move, with the LoCoBot Control Package, so I would get Align-depth.
Alternately, running Joystick Control Package and with publishing align-depth is also helpful.

Thanks in advance 

### Robot Model

locobot_base

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by lukeschmitt-tr** [comment]
To do this, modify the section in the xsarm_joy.launch file that includes the xsarm_control.launch file to set the arg `align_depth` to `true`.
```xml
    <arg name="align_depth"                        value="true"/>
```

https://github.com/Interbotix/interbotix_ros_rovers/blob/b1b5a180d31316636c58521419e0405eb5c0e249/interbotix_ros_xslocobots/examples/interbotix_xslocobot_joy/launch/xslocobot_joy.launch#L21-L33
