### ISSUE TITLE
Rplidar not working 

### ISSUE THREAD

**Issue by ajinkyamar** [Interbotix/interbotix_ros_rovers#54]
### Question

Hi
I have issue with rplidar. 

When I do installation check with the below command, no output is produced. (rplidar as expected)

ls /dev | grep rplidar

I checked the wires, and power supply but still the problem persists. 

Can anyone please help me with this? 

### Robot Model

locobot_250s 

### Operating System

Ubuntu 20.04

### ROS Version

ROS 2 Galactic

**Comment by lukeschmitt-tr** [comment]
Check that the cables are plugged into the right ports:
- The power cable should be plugged into one of the USB ports on the battery.
- The data (short micro USB) cable should be plugged directly into the NUC.

**Comment by ajinkyamar** [comment]
Thank you so much; it is working. 

I was using a longer cable to connect with NUC instead of the shorter micro USB.
