### ISSUE TITLE
[Bug]: LoCoBot keeps falling in Gazebo

### ISSUE THREAD

**Issue by moudallal** [Interbotix/interbotix_ros_rovers#59]
### What happened?

I do not have a physical LoCoBot, hence, I am using it for a project in Gazebo only. Every time I unpause the Gazebo simulation, the robot falls to and interferes with the ground. I tried running different plans and executing them for the arm in MoveIt and it does work. The momentum of the arm however keeps shifting the base back and forth, making it sway.

### Robot Model

locobot_wx200

### Operating System

Ubuntu 20.04

### ROS Distro

ROS 1 Noetic

### Steps To Reproduce

This is my first time working with LoCoBots.

1. Remote install using `$ ./xslocobot_remote_install.sh -d noetic -b create3`
2. Comment the line `export ROS_MASTER_URI=http://locobot.local:11311` in ~/.bashrc (since I do not have a physical robot)
3. In a new terminal `$ roslaunch interbotix_xslocobot_moveit xslocobot_moveit.launch robot_model:=locobot_wx200 show_lidar:=true use_gazebo:=true`
4. Unpause the simulation inside Gazebo

The same thing happens when running the following command:
`$ roslaunch interbotix_xslocobot_gazebo xslocobot_gazebo.launch robot_model:=locobot_wx250s show_lidar:=true use_trajectory_controllers:=true`

### Relevant log output

```shell
[ WARN] [1698612711.976541818, 3.113000000]: Link 'locobot/caster_back_link' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1698612711.976626259, 3.113000000]: Link 'locobot/caster_front_link' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1698612711.976647330, 3.113000000]: Link 'locobot/wheel_left_link' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1698612711.976659700, 3.113000000]: Link 'locobot/wheel_right_link' is not known to URDF. Cannot disable/enable collisons.
```

### Additional Info

I first found #12 before, but it was closed and not a lot of details were included so I made a new issue.

I do believe that the casters and wheels being not known to URDF is what is causing this issue. 

I also provided a GIF of the what is happening.
I should also mention that the `moveit_interface_gui` is not launching.

![ezgif com-video-to-gif](https://github.com/Interbotix/interbotix_ros_rovers/assets/8681312/f28bb226-7814-4272-a339-2e7a35ae0d2b)

**Comment by lukeschmitt-tr** [comment]
See if the changes in f28279d solve this for you.
