### ISSUE TITLE
[Question]: 3d scene reconstruction using SLAM

### ISSUE THREAD

**Issue by ajinkyamar** [Interbotix/interbotix_ros_rovers#61]
### Question

I need to create a 3D scene for the robot to interact with in virtual space. Can the available SLAM package create 3D reconstruction scene ( like Gaussian spatting/nerf)?  I could create point cloud map of the room using the available SLAM package.  

### Robot Model

locobot250s

### Operating System

Ubuntu 20.04

### ROS Version

ROS 2 Galactic

**Comment by lukeschmitt-tr** [comment]
The SLAM package ([rtabmap](https://github.com/introlab/rtabmap), [rtabmap_ros](https://github.com/introlab/rtabmap_ros)) does not have Gaussian Spatting/NERF capabilities as far as I know, though you can indeed create a 3D cloud representation of your environment using it as you mentioned.
