### ISSUE TITLE
[Question]: Locobot250s usage in omniverse

### ISSUE THREAD

**Issue by ajinkyamar** [Interbotix/interbotix_ros_rovers#62]
### Question

I want to know if I can use NVIDIA's ISAAC SIM omniverse to import robots and conduct experiments in its virtual environment.

### Robot Model

Locobot250s

### Operating System

Ubuntu 20.04

### ROS Version

ROS 2 Galactic

**Comment by ajinkyamar** [comment]
is there urdf file available for this robot which has physics of joints, camera etc?

**Comment by lukeschmitt-tr** [comment]
Unfortunately, there are no existing Isaac Sim configuration packages for the LoCoBot, though this may be something we add in the future.
