### ISSUE TITLE
[Question]:  Simulation in Gazebo

### ISSUE THREAD

**Issue by sanuzu** [Interbotix/interbotix_ros_rovers#66]
### Question

I used this command to start the simulation in gazebo:
roslaunch interbotix_xslocobot_gazebo xslocobot_gazebo.launch robot_model:=locobot_wx250s show_lidar:=true use_trajectory_controllers:=true

I want to the run python code on this simulation since I don't have the real robot, for example I want to run the combocontrol.py in the examples on this gazebo simulation. I am not finding instructions on how to do that . please help me.

Also I want to simulate the camera as well , is that possible ? 
My aim  is to perform object detection and have the robot perform a task (like pick the object ) all in gazebo only.
### Robot Model

locobot_wx250

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by lukeschmitt-tr** [comment]
Unfortunately, the Python-ROS API is not compatible with the Gazebo simulation at this time as stated [in the documentation](https://docs.trossenrobotics.com/interbotix_xslocobots_docs/python_interface.html). To control a Gazebo-simulated robot, you would have to use MoveIt for the arm, or by sending direct commands to individual joints. The base can be controlled via the move_base navigation package.

The camera is [simulated in Gazebo](https://github.com/Interbotix/interbotix_ros_rovers/blob/b1b5a180d31316636c58521419e0405eb5c0e249/interbotix_ros_xslocobots/interbotix_xslocobot_descriptions/urdf/pan_and_tilt.urdf.xacro#L159-L181) using the `libgazebo_ros_openni_kinect` plugin. You can find the relevant topics in the plugin configuration [here](https://github.com/Interbotix/interbotix_ros_rovers/blob/b1b5a180d31316636c58521419e0405eb5c0e249/interbotix_ros_xslocobots/interbotix_xslocobot_descriptions/urdf/pan_and_tilt.urdf.xacro#L163-L167).
