### ISSUE TITLE
[Question]: navigation stack in simulation 

### ISSUE THREAD

**Issue by sanuzu** [Interbotix/interbotix_ros_rovers#67]
### Question

Is it possible to use the navigation stack in gazebo simulation without requiring a physical robot , I am using ros noetic. If not on noetic , can it be used with ros 2?

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by lukeschmitt-tr** [comment]
See the [Navigation Configuration Sim heading](https://docs.trossenrobotics.com/interbotix_xslocobots_docs/ros1_packages/navigation_stack_configuration.html#simulation) for info on how to do this.
