### ISSUE TITLE
[Question]: Should I update the dynamixel firmware to v45?

### ISSUE THREAD

**Issue by dazednconfusing** [Interbotix/interbotix_ros_rovers#7]
### Question

Should I update the dynamixel motor firmware to v45 for each motor? Or will this break the ros modules

### Robot Model

Locobot_wx250s

### Operating System

Ubuntu 20.04

**Comment by LSinterbotix** [comment]
You should be able to update the Dynamixel firmware without any compatibility issues.

**Comment by LSinterbotix** [comment]
Do you have any further questions on this? Otherwise, this issue will be closed.
