### ISSUE TITLE
[Question]: Locobot under other file format

### ISSUE THREAD

**Issue by psykaunot** [Interbotix/interbotix_ros_rovers#71]
### Question

Hello, do you have the locobot under json format coupled with config files just like this below?
![image](https://github.com/Interbotix/interbotix_ros_rovers/assets/81990988/8058f9fe-93b7-4570-9046-72ff217e9cb4)

![image](https://github.com/Interbotix/interbotix_ros_rovers/assets/81990988/ce33350b-aa8e-4585-bde7-f7ba06dff232)

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by lukeschmitt-tr** [comment]
Could you provide a bit more context for your request? What is the json format called?

We only provide URDF-based descriptions of our robots.

**Comment by psykaunot** [comment]
The json file looks like this, it is used to for defining the properties of a robot model, possibly in a simulation or robotics application:

`
{
    "render_asset": "oreo.glb",
    "collision_asset": "oreo_collision.glb",
    "join_collision_meshes": false,
    "mass": 35.0,
    "inertia": [4.704, 1.008, 4.704],
    "friction_coefficient": 0.0,
    "restitution_coefficient": 0.0,
    "COM": [0, 0.0, 0]
}

After that, there are many configuration files, such as this one for the robot and its sensors.
![image](https://github.com/Interbotix/interbotix_ros_rovers/assets/81990988/5ccee3a4-bf4e-431a-ad2f-ddfeec5813af)


At end, it's loaded in a simulation environment as follows:

`
  <rosparam command="load" file="$(find habitat_ros)/config/oreo/oreo.yaml"/>
  <rosparam command="load" file="$(find habitat_ros)/config/oreo/VLP_16.yaml" ns="oreo/sensors/"/>
  <rosparam command="load" file="$(find habitat_ros)/config/oreo/hokuyo.yaml" ns="oreo/sensors/"/>
  <rosparam command="load" file="$(find habitat_ros)/config/oreo/rgbcam.yaml" ns="oreo/sensors/"/>
  <rosparam command="load" file="$(find habitat_ros)/config/oreo/sick_laser.yaml" ns="oreo/sensors/"/>
  <rosparam command="load" file="$(find habitat_ros)/config/oreo/fake_camera.yaml" ns="oreo/sensors/"/>
`

**Comment by lukeschmitt-tr** [comment]
As mentioned previously, we only provide URDF-based descriptions of our robots. We additionally provide tools to spawn the robots in other simulators like [Gazebo Classic](https://docs.trossenrobotics.com/interbotix_xslocobots_docs/ros1_packages/gazebo_simulation_configuration.html).

I would advise looking at the documentation for the simulator you're trying to use to see how to do the same.
